version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
