version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "4173:4173"
    restart: unless-stopped
